

# Calculate amount after discount 
def calculate_amount_after_discount(Product_Discount_Percent,product_price,Coupon_code_discount_percent,totalQuantity):
        return(product_price-(((Product_Discount_Percent+Coupon_code_discount_percent)*product_price)/100))*totalQuantity


# Calculate total amount including shipping cost ,discount ,coupon_code 
def calculate_total_price(Product_Discount_Percent,product_price,Coupon_code_discount_percent,totalQuantity, shipping_cost):
     return ((product_price-(((Product_Discount_Percent+Coupon_code_discount_percent)*product_price)/100))*totalQuantity)+shipping_cost



# This is to check and assign the shipping_cost which will be manage by the admin
def get_shipping_cost(shipping_address):
    from .models import Location  
    try:
        location = Location.objects.get(name__icontains=shipping_address)
        return location.price
    except Location.DoesNotExist:
        return 50  
    


# This is use to search the coupon_code as it is a subset of coupon generated by the admin
def get_coupon_discount(coupon_code):
    from .models import Coupon

    if not coupon_code:
        return 0  
    try:
        coupon = Coupon.objects.get(Coupon_name__icontains=coupon_code)
        return coupon.Coupon_Discount
    except Coupon.DoesNotExist:
        return 0  
    