# Generated by Django 4.2.15 on 2024-09-04 10:52

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_availability_status_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_feature_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='products.product')),
            ],
        ),
    ]
